<style>
table tr:first-child {
    background: #CECECE;
}
</style>
<div class="col-lg-12">
    <?php
    $title = 'Quản lý người dùng';
    $this->headTitle($title);
    ?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <p>
        <a href="<?php echo $this->url('adminuser', array('action'=>'add'));?>"><button class="btn btn-basic ">Thêm mới <i class="fa fa-plus" aria-hidden="true"></i></button></a>
    </p>

    <table class="table table-bordered">
    <tr>   
        <th>ID</th>
        <th>Tên đăng nhập</th>
        <th>Fullname</th>
        <th>Quyền</th>
        <th>Tùy chọn</th>
    </tr>
    <?php foreach ($this->paginator as $user) : ?>
    <tr>
        <td><?php echo $this->escapeHtml($user->id);?></td>
        <td><?php echo $this->escapeHtml($user->username);?></td>
        <td><?php echo $this->escapeHtml($user->fullname);?></td>
        <td><?php 
            if($user->level  == 1){
                echo "Admin";
            }
            else if($user->level  == 2){
                echo "Editor";
            }
            else{
                echo "Operation";
            } ?></td>
        <td>
            <a href="<?php echo $this->url('adminuser',
                array('action'=>'edit', 'id' => $user->id));?>" class="btn btn-info"><i class="fa fa-pencil" aria-hidden="true"></i></a>
            <a href="<?php echo $this->url('adminuser',
                array('action'=>'resetpassword', 'id' => $user->id));?>" class="btn btn-info"><i class="fa fa-key" aria-hidden="true"></i></a>
            <a href="<?php echo $this->url('adminuser',
                array('action'=>'delete', 'id' => $user->id));?>" class="btn btn-danger"><i class="fa fa-trash" aria-hidden="true"></i></a>
        </td>
    </tr>
    <?php endforeach; ?>
    </table>
    <?php
    echo $this->paginationControl(
        $this->paginator,
        'sliding',
        'partial/paginator.phtml',
        array(
            'route' => 'adminuser'
        )
    );
    ?>
</div>