<div class="col-lg-4">
<style>
h3 {
    height: 2em;
    background: #D2D2D2;
    line-height: 2em;
    padding: 0 1em;
    color: #000;
}

label.col-sm-9.controll-label,
label.col-sm-12.controll-label {
    margin-bottom: 2em;
    padding: 0;
    font-size: 13px;
    display: block;
}
.btn-basic{
    color: #3D3D3D;
    font-weight: bolder;
}
.error {
    padding: 0.5em 0;
    color: red;
    font-weight: normal;
}
</style>
<?php
 $title = 'Đặt lại mật khẩu';
 $this->headTitle($title);
 ?>
 <h3><?php echo $this->escapeHtml($title); ?></h3>
 <form method="post" id="forgetpassword" name="forgetpassword">
  <div class="form-group">
    <label for="username">Tài khoản</label>
    <input type="text" class="form-control" id="username" placeholder="Tài khoản" name="username">
  </div>
  <div class="form-group">
    <label for="password">Mật khẩu mới</label>
    <input type="password" class="form-control" id="password" placeholder="Mật khẩu mới" name="password">
  </div>
  <div class="form-group">
    <label for="repassword">Nhập lại mật khẩu</label>
    <input type="password" class="form-control" id="repassword" placeholder="Nhập lại mật khẩu" name="repassword">
  </div>
  <button type="submit" class="btn btn-basic">Xác nhận</button>
</form>
 <br>
 <div class="clearfix"></div>
<?php
 if ($this->messages!=""){
    echo '<br><div class="alert alert-danger">'.$messages.'</div>';
}
?>
 <br>
 <script>
    $(document).ready(function() {
        $("#forgetpassword").validate({
            rules: {
                username: {
                    required: true,
                    minlength: 6,
                    maxlength: 24,
                },
                password: {
                    required: true,
                    minlength: 5
                },
                repassword: {
                    required: true,
                    equalTo: "input[name=password]",
                    minlength: 5
                }
            },
            messages: {
                username: {
                    required: "Vui lòng nhập username",
                    minlength: "Vui lòng nhập nhiều hơn 6 ký tự",
                    maxlength: "Vui lòng nhập ít hơn 24 ký tự"
                },
                password: {
                    required: 'Vui lòng nhập mật khẩu',
                    minlength: 'Vui lòng nhập ít nhất 5 kí tự'
                },
                repassword: {
                    required: 'Vui lòng nhập mật khẩu',
                    minlength: 'Vui lòng nhập ít nhất 5 kí tự',
                    equalTo:   'Xác nhận mật khẩu mới không chính xác'
                }
            }
        });
    });    
 </script>
 </div>