<style>
label {
    float: left;
    width: 100px;
    line-height: 32px;
    font-weight: normal;
    font-size: 15px;
}
input#username {
    width: 250px;
    float: left;
}
input#btnSubmit {
    padding-left: 35px;
    padding-right: 35px;
    margin-left: 20px;
}
table tr:first-child {
    background: #CECECE;
}
</style>
<div class="col-lg-12">
<?php
$title = 'Xử lý đền bù';
$this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<form method="POST">
    <div class="form-group">
        <label for="username">Username:</label>
        <input type="text" class="form-control" id="username" value="<?php echo ($this->username=='')?'':$this->username; ?>" name="username">
    </div>
    <div class="form-group">
        <input type="submit" class="btn btn-basic" id="btnSubmit">
    </div>
</form>
<div class="clearfix"></div>
<?php 
     if ($this->error!=""){
        echo '<br><div class="alert alert-danger">';
            echo $this->error;
        echo '</div>';
    }
    if($this->result!=""){?>
    <div class="clearfix"></div>
    <table class="table table-bordered">
    <tr>   
        <td>ID</td>
        <td>Username</td>
        <td>Email</td>
        <td>Họ tên</td>
        <td>Số điện thoại</td>
        <td>Option</td>
    </tr>
    <tr>
        <td><?php echo $result->id?></td>
        <td><?php echo $result->username?></td>
        <td><?php echo $result->email?></td>
        <td><?php echo $result->fullname?></td>
        <td><?php echo $result->mobile?></td>
        <td><a href="<?php echo $this->url('gamer', array('action'=>'compensation', 'id'=>$result->id, 'username'=>$result->username));?>"><button class="btn btn-basic ">Đền bù</button></a></td>
    </tr>
    </table>
<?php } ?>