<style>
label {
    float: left;
    width: 100px;
    line-height: 32px;
    font-weight: normal;
    font-size: 15px;
}
input#username {
    width: 250px;
    float: left;
}
input#btnSubmit {
    padding-left: 35px;
    padding-right: 35px;
    margin-left: 20px;
}
table tr:first-child {
    background: #CECECE;
}
table tr td:first-child {
    width: 25%;
    background: #CECECE;
}
</style>
<div class="col-lg-12">
<?php
$title = 'Thông tin user passport';
$this->headTitle($title);
?>
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active" aria-current="page">Thông tin user passport</li>
  </ol>
</nav>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<form method="POST" action = 'info'>
    <div class="form-group">
        <label for="username">Username:</label>
        <input type="text" class="form-control" id="username" value="<?php echo ($this->username=='')?'':$this->username; ?>" name="username">
    </div>
    <div class="form-group">
        <input type="submit" class="btn btn-basic" id="btnSubmit">
    </div>
</form>
<div class="clearfix"></div>
<?php 
     if ($this->error!=""){
        echo '<br><div class="alert alert-danger">';
            echo $this->error;
        echo '</div>';
    }
    if ($this->success!=""){
        echo '<br><div class="alert alert-success">';
            echo $this->success;
        echo '</div>';
    }
    if($this->result!=""){?>
    <div class="clearfix"></div>
    <table class="table table-bordered">
    <tr>   
        <td>Tên trường</td>
        <td>Giá trị</td>
    </tr>
    <tr>   
        <td>User ID</td>
        <td><?php echo $result->id?></td>
    </tr>
    <tr>   
        <td>Email</td>
        <td><?php echo $result->email?></td>
    </tr>
    <tr>   
        <td>Họ tên</td>
        <td><?php echo $result->fullname?></td>
    </tr>
    <tr>   
        <td>Ngày sinh</td>
        <td><?php echo $result->birthday?></td>
    </tr>
    <tr>   
        <td>Giới tính</td>
        <td><?php if($result->sex==1) echo'Nam';else echo 'Nữ';?></td>
    </tr>
    <tr>   
        <td>Số CMND</td>
        <td><?php echo $result->identityNumber?></td>
    </tr>
    <tr>   
        <td>Ngày cấp CMND</td>
        <td><?php echo $result->identityDate?></td>
    </tr>
    <tr>   
        <td>Nới cấp CMND</td>
        <td><?php echo $result->identityPlace?></td>
    </tr>
    <tr>   
        <td>Số điện thoại</td>
        <td><?php echo $result->mobile?></td>
    </tr>
    <tr>   
        <td>Địa chỉ</td>
        <td><?php echo $result->address?></td>
    </tr>
    <tr>   
        <td>Thành phố</td>
        <?php 
            $str = file_get_contents('./data/city.json');
            $json = json_decode($str, true);
            $namecity = '';
            foreach ($json as  $person_a) {
                if($person_a['code']===$result->city)
                    $namecity = $person_a['name'];
            }
        ?>
        <td><?php echo $namecity?></td>
    </tr>
    <tr>   
        <td>Tên công ty</td>
        <td><?php echo $result->company?></td>
    </tr>
    <tr>   
        <td>Địa chỉ công ty</td>
        <td><?php echo $result->companyAddress?></td>
    </tr>
    <tr>   
        <td>Ngày tạo</td>
        <td><?php echo $result->createDate?></td>
    </tr>
    <tr>   
        <td>Lần đăng nhập gần nhất</td>
        <td><?php echo $result->lastLogin?></td>
    </tr>
    <tr>   
        <td>Địa chỉ ip</td>
        <td><?php echo $result->ip?></td>
    </tr>
    <tr>   
        <td>status</td>
        <td><?php if($result->status==1) echo'Đang hoạt động';else echo 'Ẩn';?></td>
    </tr>
    </table>
    <td><a href="<?php echo $this->url('gamer', array('action'=>'updateinfo', 'id'=>$result->username));?>"><button class="btn btn-basic ">Cập nhập thông tin</button></a></td>
    <form action="" method = 'post' style="display: unset">
    <input type="hidden" name = "username" value = '<?php echo $result->username?>'/>            
    <?php if($result->status==1){?>
    <input type="hidden" name = "status" value = '1'/>
    <td><button class="btn btn-basic " type="submit">Chuyển status thành ẩn</button></td>
    <?php }else{?>
    <input type="hidden" name = "status" value = '2' type="submit"/>    
    <td><button class="btn btn-basic ">Chuyển status thành đang hoạt động</button></td>    
    <?php }?>
    </form>
<?php } ?>