<html lang="en">
<head>
<?php echo $this->headTitle('message'. $this->translate('100d Pay'))->setSeparator(' - ')->setAutoEscape(false) ?>
<?php echo $this->headMeta()
    ->setCharset('UTF-8')
    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
?>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
<style>
.form-gap {
    padding-top: 70px;
}
.panel-body p {
    font-size: 13px;
    font-weight: bold;
    font-style: italic;
    color: red;
}
</style>
</head>
<body>
    <div class="form-gap"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="text-center">
                        <h3><i class="fa fa-lock fa-4x"></i></h3>
                        <h2 class="text-center">Chuyển hướng thất bại</h2>
                        <p>Lỗi - <?php echo $status?> : <?php echo $message?></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
