<style>
.col-sm-12{
    padding-right: 0px;
    padding-left: 0px;
}
</style>
<?php

 $title = 'Đổi mật khẩu mới';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <div class="col-md-4">
 <?php
 $form->setAttribute('action', $this->url('setpassword'));

 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formRow($form->get('newpassword'));
 echo $this->formRow($form->get('renewpassword'));
 echo $this->formRow($form->get('submit')); 
 if ($this->messages){
     echo '<br><div class="alert alert-danger">';
     foreach($this->messages as $message)
     { 
         echo $message;
     }
     echo '</div>';
 }
 echo $this->form()->closeTag();
 ?>
 </div>