<style>
.controll-label {
    width: 100%;
    display: block;
    line-height: 2em;
    padding: 0;
    margin: 0;
}
.form-control {
    box-shadow: none;
    height: 35px;
    padding: 6px;
    border: solid 1px #bfbfbf;
    border-radius: 4px;
    background-color: #fff;
}
.exist-account {
    line-height: 40px;
    font-size: 16px;
    width: 100%;
    text-align: center;
}
input#submitbutton {
    background: #0e90d2;
    border: 0;
    color: #fff;
    margin-top: 1em;
    width: 30%;
    padding: 8px;
    display: block;
    text-transform: uppercase;
}
label span {
    font-weight: bolder;
    color: #444;
}
@media only screen and (max-width: 420px){
    input#submitbutton {
        width: 50%;
    }
}
</style>
<?php
 $title = 'Đổi mật khẩu';
 $this->headTitle($title);
 ?>
 <h3><?php echo $this->escapeHtml($title); ?></h3>
 <?php
 $form->prepare();
 echo $this->form()->openTag($form);
 echo $this->formRow($form->get('password'));
 echo $this->formRow($form->get('newpassword'));
 echo $this->formRow($form->get('renewpassword'));
 echo $this->formSubmit($form->get('submit'));
 echo "<div id='loading'><i class='fa fa-spinner fa-spin'></i></div>";
 echo $this->form()->closeTag();
 echo "<div class='clearfix'></div>";
 if ($this->messages!=""){
    echo '<br><div class="alert alert-info">'.$messages.'</div>';
}?>
<script>
$(document).ready(function() {
    $(window).on('beforeunload', function(){
        $("#loading").show();   
    });
    
    $("#user").validate({
        rules: {
            password: {
                required: true,
                minlength: 5
            },
            newpassword: {
                required: true,
                minlength: 5
            },
            renewpassword: {
                required: true,
                equalTo: "input[name=newpassword]",
                minlength: 5
            }
            
        },
        messages: {
            password: {
                required: 'Vui lòng nhập mật khẩu',
                minlength: 'Vui lòng nhập ít nhất 5 kí tự'
            },
            newpassword: {
                required: 'Vui lòng nhập mật khẩu',
                minlength: 'Vui lòng nhập ít nhất 5 kí tự'
            },
            renewpassword: {
                required: 'Vui lòng nhập mật khẩu',
                minlength: 'Vui lòng nhập ít nhất 5 kí tự',
                equalTo:   'Xác nhận mật khẩu mới không chính xác'
            }
        }
    });
});
</script>