<html lang="en">
<head>
<?php echo $this->headTitle('Reset password '. $this->translate('100d Pay'))->setSeparator(' - ')->setAutoEscape(false) ?>
<?php echo $this->headMeta()
    ->setCharset('UTF-8')
    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
?>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
<script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<style>
.form-gap {
    padding-top: 70px;
}
.panel-body p {
    font-size: 12px;
    font-weight: bold;
    font-style: italic;
    color: red;
}
</style>
</head>
<body>
    <div class="form-gap"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="panel panel-default">
                <div class="panel-body">
                    <div class="text-center">
                    <h3><i class="fa fa-lock fa-4x"></i></h3>
                    <h2 class="text-center">Reset password</h2>
                    <p><?php echo $this->data?></p>
                    <div class="panel-body">
                        <form id="reset-form" role="form" autocomplete="off" class="form" method="post">
                            <div class="form-group">
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-asterisk color-blue"></i></span>
                                    <input id="password" name="password" placeholder="New password" class="form-control"  type="password" autocomplete="off">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-refresh color-blue"></i></span>
                                    <input id="repassword" name="repassword" placeholder="Re new password" class="form-control"  type="password" autocomplete="off">
                                </div>
                            </div>
                            <div class="form-group">
                            <input name="recover-submit" class="btn btn-lg btn-primary btn-block" value="Reset Password" onclick="myFunction()" type="button">
                            </div>
                            
                            <input type="hidden" class="hide" name="username" id="username" value="<?php echo $this->username?>"> 
                            <input type="hidden" class="hide" name="secretKey" id="secretKey" value="<?php echo $this->secretKey?>"> 
                        </form>
        
                    </div>
                    </div>
                </div>
                </div>
            </div>
        </div>
    </div>
    <script>
    function myFunction() {
        var password = $("#password").val();
        var confirmPassword = $("#repassword").val();
        if (password == '' || confirmPassword == '')
            $(".panel-body p").html("Hãy nhập đầy đủ các trường");
        else if (password != confirmPassword)
            $(".panel-body p").html("Mật khẩu không trùng nhau");
        else{
            document.getElementById("reset-form").submit();
        }
    }
    </script>
</body>
</html>
