<div class="col-lg-12">
<style>
h3 {
    height: 2em;
    background: #D2D2D2;
    line-height: 2em;
    padding: 0 1em;
    color: #000;
}
h5.mb-1 {
    font-weight: bold;
}

.d-flex.w-100.justify-content-between {
    width: 200px;
    float: left;
}

p.mb-1 {
    float: left;
    width: 500px;
    line-height: 30px;
}

.list-group-item.list-group-item-action.flex-column.align-items-start {
    height: 50px;
    font-size: 14px;
    line-height: 25px;
}
</style>
<?php
 $title = 'Detail transaction';
 $this->headTitle($title);
 ?>
 <h3><?php echo $this->escapeHtml($title); ?></h3>

 <div class="list-group">
    <div class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1">Mã giao dịch</h5>
        </div>
        <p class="mb-1"><?php echo $this->result[0]->transaction_id?></p>
    </div>
    <div class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1">UserId</h5>
        </div>
        <p class="mb-1"><?php echo $this->result[0]->uid?></p>
    </div>
    <div class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1">Username</h5>
        </div>
        <p class="mb-1"><?php echo $this->result[0]->username?></p>
    </div>
    <div class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1">Server ID:</h5>
        </div>
        <p class="mb-1"><?php echo $this->result[0]->server_id?></p>
    </div>
    <div class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1">Product ID:</h5>
        </div>
        <p class="mb-1"><?php echo $this->result[0]->product_id?></p>
    </div>
    <div class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1">Mệnh giá:</h5>
        </div>
        <p class="mb-1"><?php echo ($this->result[0]->order_vnd!='')?number_format($this->result[0]->order_vnd):''; ?></p>
    </div>
    <div class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1">Trị giá:</h5>
        </div>
        <p class="mb-1"><?php echo ($this->result[0]->order_amount!='')?number_format($this->result[0]->order_amount):''; ?></p>
    </div>
    <div class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1">Thời gian</h5>
        </div>
        <p class="mb-1"><?php echo $this->result[0]->created_at?></p>
    </div>
    <div class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1">Payload</h5>
        </div>
        <p class="mb-1"><?php echo $this->result[0]->payload?></p>
    </div>
    <div class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1">Agent</h5>
        </div>
        <p class="mb-1"><?php echo $this->result[0]->agent?></p>
    </div>
    
    <div class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1">Trạng thái:</h5>
        </div>
        <p class="mb-1"><?php echo ($this->result[0]->status==1)?'Thành công':'Thất bại';  ?></p>
    </div>
    <div class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1">OS</h5>
        </div>
        <p class="mb-1"><?php echo $this->result[0]->os?></p>
    </div>
 </div>