<link rel="stylesheet" type="text/css" media="all" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-daterangepicker/2.1.27/daterangepicker.min.css" />

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-daterangepicker/2.1.27/moment.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-daterangepicker/2.1.27/daterangepicker.min.js"></script>
<style>
table tr:first-child {
    background: #CECECE;
}
label.controll-label.col-sm-2 {
    width: 200px;
}

#config-form {
    width: 200px;
    display: unset;
}

#config-demo {
    width: 200px;
}
.box-row {
    width: 33%;
    float: left;
    padding-top: 1em;
}
#submitbutton {
    margin-left: 15px;
    margin-bottom: 1em;
    width: 200px;
}
.btn-export {
    margin: 1em 0;
}
</style>
<div class="col-lg-12">
    <?php
    $title = 'Lịch sử nạp game';
    $this->headTitle($title);
    ?>
    <h3><?php echo $this->escapeHtml($title); ?></h3>
    <?php
    $form = $this->form;
    $form->prepare();
    echo $this->form()->openTag($form);
    echo "<div class='box-row'>";
    echo $this->formRow($form->get('in_transaction'));
    echo "</div>";
    echo "<div class='box-row'>";
    echo $this->formRow($form->get('in_product_id'));
    echo "</div>";
    echo "<div class='box-row'>";
    echo $this->formRow($form->get('in_server'));
    echo "</div>";
    echo "<div class='box-row'>";
    echo $this->formRow($form->get('in_status'));
    echo "</div>";
    echo "<div class='box-row'>";
    echo $this->formRow($form->get('in_time'));
    echo "</div>";
    echo "<div class='box-row'>";
    echo $this->formRow($form->get('in_type'));
    echo "</div>";
    echo "<div class='box-row'>";
    echo $this->formRow($form->get('in_username'));
    echo "</div>";
    echo "<div class='box-row'>";
    echo $this->formRow($form->get('in_role'));
    echo "</div>";
    echo "<div class='box-row'>";
    echo $this->formRow($form->get('in_serial'));
    echo "</div>";
    echo "<div class='box-row'>";
    echo $this->formRow($form->get('in_code'));
    echo "</div>";
    echo "<div class='box-row'>";
    echo $this->formSubmit($form->get('submit'));
    echo "</div>";
    echo $this->form()->closeTag();
    if($this->result!=null){
        echo '<a class="btn btn-success btn-export" href="/admin/statistic/exportpay">Export Excel</a>';
    }?>
    <hr>
    <div class="clearfix"></div>
    <h5><b style="margin-right:20px;"><u>Tổng tiền đã nạp: 
    <?php if(isset($this->total))
       echo number_format($this->total);
    else
       echo '0';?>
    </u></b>
	<b><u>Tổng gold đã nạp: 
    <?php if(isset($this->totalGold))
       echo number_format($this->totalGold);
    else
       echo '0';?>
    </u></b>
	</h5>
    <table class="table table-bordered">
    <tr>   
        <td>Transaction ID</td>
        <td>Loại thẻ</td>
        <td>Username</td>
        <td>Role Name</td>
        <td>Mệnh giá</td>
        <td>Giá trị duy đổi</td>
        <td>Mã lỗi trừ tiền</td>
        <td>Thông báo trừ tiền</td>
        <td>Game</td>
        <td>Server</td>
        <td>Thông báo nạp vào game</td>
        <td>Mã lỗi nạp vào game</td>
        <td>Ngày thực hiện</td>	
    </tr>
    <?php if($this->result!=null){foreach ($this->result as $row) : ?>
    <tr>
        <td><a href="<?php echo '/admin/statistic/detailpayGetHistory?id='.$row->transaction_id;?>" target="_blank"><?php echo $row->transaction_id?></a></td>
        <td><?php echo $row->card_type?></td>
        <td><?php echo $row->username?></td>
        <td><?php echo $row->role?></td>
        <td><?php echo ($row->amount!='')?number_format($row->amount):''?></td>
        <td><?php echo ($row->gold!='')?number_format($row->gold):''?></td>
        <td><?php echo $row->card_status?></td>
        <td><?php echo $row->card_message?></td>
        <td><?php 
        for($i=0; $i < count($this->products); $i++){
            if($this->products[$i]['agent']==$row->product_id)
                echo $this->products[$i]['name'];
        }
        ?></td>
        <td><?php 
        for($i=0; $i < count($this->servers); $i++){
            if($this->servers[$i]['server_id']==$row->server_id)
                echo $this->servers[$i]['server_name'];
        }
        ?></td>
        <td><?php echo ($row->pay==1)?'Nạp vào game thành công':'Nạp vào game thất bại'; ?></td>
        <td><?php echo $row->pay?></td>
        <td><?php echo $row->create_date?></td>
    </tr>
    <?php endforeach; }else{ echo "<tr><td colspan='13'>Không có dữ liệu</td></tr>";}?>
    </table>
    <?php if(isset($this->pages)){ ?>
    <ul class="pagination">
        <?php for($i = 1; $i <= (int) $this->pages ; $i++){?>
        <?php if($this->current_page == $i){?>
            <li class="active"><a href="<?php echo '/admin/statistic/payGetHistory?page='.$this->current_page;?>"><?php echo $this->current_page ?></a></li>
        <?php }else{?>
            <li><a href="<?php echo '/admin/statistic/payGetHistory?page='.$i;?>"><?php echo $i ?></a></li>
        <?php } }?>
    </ul>
    <?php } ?>
</div>
<script type="text/javascript">
	$(document).ready(function() { 
		updateConfig();
		function updateConfig() { 
			$('#config-demo').daterangepicker({
                format: 'dd/mm/yyyy',
                <?php if(!$status){?>
                startDate: moment().subtract(0, 'day')
                <?php }?>
            }); 
		}
	});
    $('.in_product_id').on('change', function(){
        if($(this).val()!='')
            window.location = '/admin/statistic/payGetHistory/' + $(this).val();
        else
            window.location = '/admin/statistic/payGetHistory';   
    });
</script>