<div class="col-lg-12">
<style>
h3 {
    height: 2em;
    background: #D2D2D2;
    line-height: 2em;
    padding: 0 1em;
    color: #000;
}

label.col-sm-9.controll-label,
label.col-sm-12.controll-label {
    margin-bottom: 2em;
    padding: 0;
    font-size: 13px;
    display: block;
}
.btn-basic{
    color: #3D3D3D;
    font-weight: bolder;
}
.error {
    padding: 0.5em 0;
    color: red;
    font-weight: normal;
}
.divHidden {
    display: none;
}
</style>
<?php
 
 $title = 'Chỉnh sửa loại thẻ thanh toán';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'adminchargetype',
     array(
         'action' => 'edit',
         'id'     => $this->id,
     )
 ));
 $form->prepare();
 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('type'));
 echo "<div class='clearfix'></div>";
 echo $this->formRow($form->get('name'));
 echo "<div class='clearfix'></div>";
 echo $this->formRow($form->get('status'));
 echo "<div class='clearfix'></div>";
 echo "<hr>".$this->formRow($form->get('submit'));
 echo $this->form()->closeTag();
 ?>
 <br>
 <br>
 <br>
 <br>
 <br>
 <br>
 <br>
 <script>    CKEDITOR.replace('content');</script>
 <script>
    $(document).ready(function() {
        $("#chargeType").validate({
            rules: {
                type: {
                    required: true,
                },
                name: {
                    required: true,
                },
                status: {
                    required: true,
                },
            },
            messages: {
                type: {
                    required: "Vui lòng nhập loại thẻ",
                },
                name: {
                    required: "Vui lòng nhập tên loại thẻ",
                },
                status: {
                    required: "Vui lòng chọn trạng thái",
                },
            }
        });
    });    
 </script>
 </div>