<style>
thead {
    background: #CECECE;
}
.form-control {
    width: 50px;
    text-align: center;
}
</style>
<div class="col-lg-12">
    <?php
    $title = 'Quản lý loại thẻ thanh toán';
    $this->headTitle($title);
    ?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <p>
        <a href="<?php echo $this->url('adminchargetype', array('action'=>'add'));?>"><button class="btn btn-basic ">Thêm mới <i class="fa fa-plus" aria-hidden="true"></i></button></a>
    </p>
    <table id="datatables" class="table table-striped table-bordered" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>ID</th>
            <th>Loại thẻ</th>
            <th>Tên loại thẻ</th>
            <th>Trạng thái</th>
            <th>Ngày tạo</th>
            <th>Ngày cập nhập</th>
            <th>Tùy chọn</th>
        </tr>
    </thead>
    <tbody>
    
    <?php foreach ($chargeTypes as $row) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($row->id);?></td>=
            <td><?php echo $this->escapeHtml($row->type);?></td>
            <td><?php echo $this->escapeHtml($row->name);?></td>
            <td><?php echo ($row->status == 1) ? 'Hiển thị' : 'Ẩn';?></td>
            <td><?php echo date('H:i d-m-Y', strtotime($row->created_at)) ?>
            <td><?php echo date('H:i d-m-Y', strtotime($row->updated_at)) ?>
            <td>
                <a href="<?php echo $this->url('adminchargetype',
                    array('action'=>'edit', 'id' => $row->id));?>" class="btn btn-info"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                <a href="<?php echo $this->url('adminchargetype',
                    array('action'=>'delete', 'id' => $row->id));?>" class="btn btn-danger"><i class="fa fa-trash" aria-hidden="true"></i></a>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
    </table>
</div>
<script>
    $(document).ready(function() {
        $('#datatables').DataTable( {
            "select": true,
            "pageLength": 50
        } );
    } );    
</script>