<div class="col-lg-9">
<style>
h3 {
    height: 2em;
    background: #D2D2D2;
    line-height: 2em;
    padding: 0 1em;
    color: #000;
}

label.col-sm-12.controll-label {
    margin-bottom: 2em;
    padding: 0;
    font-size: 13px;
}
.btn-basic{
    color: #3D3D3D;
    font-weight: bolder;
}
.error {
    padding: 0.5em 0;
    color: red;
    font-weight: normal;
}
label.col-sm-9.controll-label {
    padding: 0;
}
</style>
<?php

 $title = 'Đổi mật khẩu';
 $this->headTitle($title);
 ?>
 <h3><?php echo $this->escapeHtml($title); ?></h3>
 <?php
 $form->setAttribute('action', $this->url('changepassword'));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formRow($form->get('password'));
 echo $this->formRow($form->get('newpassword'));
 echo $this->formRow($form->get('renewpassword'));
 echo "<div class='clearfix'></div>";
 echo $this->formRow($form->get('submit')); 
 echo $this->form()->closeTag();
 if ($this->messager!=""){
    echo '<div class="clearfix"></div><br><div class="alert alert-danger">';
        echo $this->messager;
    echo '</div>';
}
?>
</div>