<div class="col-lg-12">
<script src="https://cdnjs.cloudflare.com/ajax/libs/canvasjs/1.7.0/canvasjs.js"></script>
<style>
#chartContainer, #chartContainer2 {
    display: block;
    min-height: 30em;
    width: 50%;
    float: left;
}
@media(max-width:768px) {
    #chartContainer, #chartContainer2 {
		display: block;
		min-height: 30em;
		width: 100%;
		float: unset !important;
	}
}
</style>
	<div id="chartContainer"></div>

	<script type="text/javascript">
	$(function () {
	var chart = new CanvasJS.Chart("chartContainer", {
		animationEnabled: true,
		title: {
			text: "Thống kê bài viết"
		},
		data: [
		{
			type: "column",                
			dataPoints: <?php echo json_encode($this->thongkebaiviet, JSON_NUMERIC_CHECK); ?>
		}
		]
	});
	chart.render();
	});
	</script>
	<div id="chartContainer2"></div>
    
	<script type="text/javascript">
	$(function () {
	var chart2 = new CanvasJS.Chart("chartContainer2", {
		animationEnabled: true,
		title: {
			text: "Thống kê bài viết thuộc nhóm bài viết"
		},
		data: [
		{
			type: "pie",                
			dataPoints: <?php echo json_encode($this->thongkebaivietcategory, JSON_NUMERIC_CHECK); ?>
		}
		]
	});
	chart2.render();
	});
	</script>
</div>
<div class="clearfix"></div>