<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.js"></script> 
<style>
thead {
    background: #CECECE;
}
input.form-control {
    width: 50px;
    text-align: center;
}
</style>
<script>
    $(document).ready(function() {
        $('#datatables').DataTable( {
            "select": true,
            "pageLength": 50,
            "order": [[ 1, "asc" ]]
        } );
    } );    
</script>
<div class="col-lg-12">
    <?php
    $title = 'Quản lý game';
    $this->headTitle($title);
    ?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <h5><i>*** &nbsp; Kéo thả để sắp xếp thứ tự product</i></h5>
    <p>
        <a href="<?php echo $this->url('adminproduct', array('action'=>'add'));?>"><button class="btn btn-basic ">Thêm mới <i class="fa fa-plus" aria-hidden="true"></i></button></a>
    </p>
    <table id="datatables" class="table table-striped table-bordered" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>ID</th>
            <th>Sắp xếp</th>
            <th>Tên game</th>
            <th>Agent</th>
            <th>Ảnh đại diện</th>
            <th>Ngày tạo</th>
            <th>Cập nhập lần cuối bởi</th> 
            <th>Trạng thái</th> 
            <th>Loại payment</th> 
            <th>Tùy chọn</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($product as $row) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($row->id);?></td>
            <input type="hidden" value="<?php echo $row->id?>" id="id_product"/>
            <td><?php echo $row->order?><input type="text" value="<?php echo $row->order?>" class="form-control" readonly="true" id="order_product" style="display: none;"/></td>
            <td><?php echo $this->escapeHtml($row->name);?></td>
            <td><?php echo $this->escapeHtml($row->agent);?></td>
            <td><img src="/img/icon/<?php echo $this->escapeHtml($row->avatar);?>" alt="" class="img-responsive"/></td>
            <td><?php echo date('H:i d-m-Y', strtotime($row->created_at)) ?>
            <td><?php echo $this->escapeHtml($row->username);?></td>
            <td><?php if($row->status == 1) echo 'Hiện'; else echo 'Ẩn';?></td>
            <td><?php if($row->payment_type == 1) echo 'Thanh toán không cần ví'; else if($row->payment_type == 2) echo 'Thanh toán bằng ví'; else echo 'Bảo trì hoặc chưa phát hành';?></td>
            <td>
                <a href="<?php echo $this->url('adminproduct',
                    array('action'=>'edit', 'id' => $row->id));?>" class="btn btn-info"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                <a href="<?php echo $this->url('adminproduct',
                    array('action'=>'delete', 'id' => $row->id));?>" class="btn btn-danger"><i class="fa fa-trash" aria-hidden="true"></i></a>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
    </table>
</div>
<script type="text/javascript">
    $('tbody').sortable({
        items: 'tr',
        start: function(event, ui) {
            // Create a temporary attribute on the element with the old index
            current_position = (ui.item.index()+1);
            id_current_position = $(this).find("input[type=hidden]").val();
        },
        update: function(event, ui) {
            let desired_position = (ui.item.index()+1);
            console.log('desired_position: '+desired_position);
            console.log('id_current_position: '+id_current_position);
            console.log('current_position: '+current_position);
            //Post to the server to handle the changes
            $.ajax({
                type: "POST",
                url: "/admin/product/sort",
                data: {
                    desired_position: desired_position,
                    current_position: current_position,
                    id_current_position: id_current_position
                },
                beforeSend: function() {
                    // Disable dragging
                    $('tbody').sortable('disable');
                },
                success: function(html) {
                    // Re-enable dragging
                    location.reload();
                    $('tbody').sortable('enable');
                }
            });
        }
    });
</script>