<style>
thead {
    background: #CECECE;
}
input.form-control {
    width: 50px;
    text-align: center;
}
</style>
<div class="col-lg-12">
    <?php
    $title = 'Quản lý gold';
    $this->headTitle($title);
    ?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <p>
        <a href="<?php echo $this->url('admingold', array('action'=>'add'));?>"><button class="btn btn-basic ">Thêm mới <i class="fa fa-plus" aria-hidden="true"></i></button></a>
    </p>
    <table id="datatables" class="table table-striped table-bordered" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>ID</th>
            <th>Ảnh đại diện</th>
            <th>Amount</th>
            <th>Gold</th>
            <th>Product</th>
            <th>Ngày tạo</th>
            <th>Tùy chọn</th>
        </tr>
    </thead>
    <tbody>
    
    <?php foreach ($gold as $row) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($row->id);?></td>
            <td><img src="/img/iconcoin/<?php echo $this->escapeHtml($row->image);?>" alt="" class="img-responsive"/></td>
            <td><?php echo $this->escapeHtml($row->amount);?></td>
            <td><?php echo $this->escapeHtml($row->gold);?></td>
            <td><?php 
            for($i=0; $i < count($this->products); $i++){
                if($this->products[$i]['agent']==$row->product_id)
                    echo $this->products[$i]['name'];
            }
            ?>
            </td>
            <td><?php echo date('H:i d-m-Y', strtotime($row->created_at)) ?>
            <td>
                <a href="<?php echo $this->url('admingold',
                    array('action'=>'edit', 'id' => $row->id));?>" class="btn btn-info"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                <a href="<?php echo $this->url('admingold',
                    array('action'=>'delete', 'id' => $row->id));?>" class="btn btn-danger"><i class="fa fa-trash" aria-hidden="true"></i></a>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
    </table>
</div>
<script>
    $(document).ready(function() {
        $('#datatables').DataTable( {
            "select": true,
            "pageLength": 50
        } );
    } );    
</script>